// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/heartbeat": {
            "get": {
                "description": "return heartbeat status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heartbeat"
                ],
                "summary": "Check Heartbeat of the Service",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/version.ResponseVersion"
                        }
                    }
                }
            }
        },
        "/transactions/get": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get All Transactions Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/transactions.Transactions"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseRestApi"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseRestApi"
                        }
                    }
                }
            }
        },
        "/transactions/get/aggregate": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get The Aggregate Of Transactions Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/transactions.TransactionsAggregateContent"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseRestApi"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseRestApi"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ResponseRestApi": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "transactions.AggregateGroup": {
            "type": "object",
            "properties": {
                "avg": {
                    "type": "number"
                },
                "collection": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "max": {
                    "type": "integer"
                },
                "median": {
                    "type": "integer"
                },
                "min": {
                    "type": "integer"
                }
            }
        },
        "transactions.Transactions": {
            "type": "object",
            "properties": {
                "paid_amount": {
                    "type": "integer"
                },
                "paid_usd": {
                    "type": "string"
                },
                "payment_method": {
                    "type": "integer"
                },
                "transaction_date": {
                    "type": "integer"
                },
                "transaction_hash": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "transactions.TransactionsAggregateContent": {
            "type": "object",
            "properties": {
                "paid": {
                    "$ref": "#/definitions/transactions.AggregateGroup"
                },
                "payment_method": {
                    "type": "integer"
                }
            }
        },
        "version.ResponseVersion": {
            "type": "object",
            "properties": {
                "last_check": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
