// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/heartbeat": {
            "get": {
                "description": "return heartbeat status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "heartbeat"
                ],
                "summary": "Check Heartbeat of the Service",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/version.ResponseVersion"
                        }
                    }
                }
            }
        },
        "/komoditas/get": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "komoditas"
                ],
                "summary": "Get All Komoditas Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/komoditas.Komoditas"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseRestApi"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseRestApi"
                        }
                    }
                }
            }
        },
        "/komoditas/get/aggregate": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "komoditas"
                ],
                "summary": "Get The Aggregate Of Komoditas Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/komoditas.KomoditasAggregateContent"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseRestApi"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseRestApi"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "komoditas.AggregateGroup": {
            "type": "object",
            "properties": {
                "avg": {
                    "type": "number"
                },
                "collection": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "max": {
                    "type": "integer"
                },
                "median": {
                    "type": "integer"
                },
                "min": {
                    "type": "integer"
                }
            }
        },
        "komoditas.Komoditas": {
            "type": "object",
            "properties": {
                "area_kota": {
                    "type": "string"
                },
                "area_provinsi": {
                    "type": "string"
                },
                "komoditas": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "price_usd": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "tgl_parsed": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "komoditas.KomoditasAggregateContent": {
            "type": "object",
            "properties": {
                "price": {
                    "$ref": "#/definitions/komoditas.AggregateGroup"
                },
                "size": {
                    "$ref": "#/definitions/komoditas.AggregateGroup"
                },
                "week_number": {
                    "type": "integer"
                }
            }
        },
        "models.ResponseRestApi": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "version.ResponseVersion": {
            "type": "object",
            "properties": {
                "last_check": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
