definitions:
  models.ResponseRestApi:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
  transactions.AggregateGroup:
    properties:
      avg:
        type: number
      collection:
        items:
          type: integer
        type: array
      max:
        type: integer
      median:
        type: integer
      min:
        type: integer
    type: object
  transactions.Transactions:
    properties:
      paid_amount:
        type: integer
      paid_usd:
        type: string
      payment_method:
        type: integer
      transaction_date:
        type: integer
      transaction_hash:
        type: string
      username:
        type: string
    type: object
  transactions.TransactionsAggregateContent:
    properties:
      paid:
        $ref: '#/definitions/transactions.AggregateGroup'
      payment_method:
        type: integer
    type: object
  version.ResponseVersion:
    properties:
      last_check:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
paths:
  /heartbeat:
    get:
      consumes:
      - application/json
      description: return heartbeat status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/version.ResponseVersion'
      summary: Check Heartbeat of the Service
      tags:
      - heartbeat
  /transactions/get:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/transactions.Transactions'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseRestApi'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseRestApi'
      security:
      - JWT: []
      summary: Get All Transactions Data
      tags:
      - transactions
  /transactions/get/aggregate:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/transactions.TransactionsAggregateContent'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseRestApi'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ResponseRestApi'
      security:
      - JWT: []
      summary: Get The Aggregate Of Transactions Data
      tags:
      - transactions
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
