logger:
  dailyRotate: true
  compressLog: true
  logToTerminal: true
databases:
  redis:
    host: localhost:6379
    auth: uniquepassword
    db: 0
    max_idle: 80
    max_active: 12000
    status: false
  postgre:
    host: localhost
    port: 5432
    user: root
    pass: uniquepassword
    db: fetch-app
    schema: public
    status: false
  mongo:
    host:
      '0': localhost:27017
    user: root
    pass: uniquepassword
    db: admin
    srv: false
    cluster: false
    rs_name: admin
    status: false
  sqlite:
    path: ./db
    file: fetch_app.db
    status: true
services:
  cronjob:
    status: true
    jobs:
      exchangerates:
        status: true
        every: day
        hours:
          - "00:00"
          - "08:00"
          - "16:00"
  daemon:
    sleep: 10
    waitGroup: true
    status: false
  restapi:
    port: '8600'
    base_path: "/api/v1/fetch-app"
    swagger:
      title: "Fetch App"
      description: "Fetch Application Documentation"
      schemes: 
        - "http"
    status: true
  kafka:
    brokers:
      '1': localhost:9092
    assignor: roundrobin
    version: 2.1.1
    verbose: false
    dialTimeout: 2
    consumer:
      type: group
      topic: t-favorites
      group: cg-t-favorites
      oldest: true
      status: false
    publisher:
      retrymax: 2
      timeout: 2
      idempotent: true
      status: false
  prometheus:
    status: false
etc:
  endpoints:
    data_app: http://localhost:8900/api/v1/data-app
    auth_app: http://localhost:8800/api/v1/auth-app
    currencyconverter_api: https://api.apilayer.com/exchangerates_data
    currencyconverter_api_key: lZifniNg3yjCKvlvfKuJHgrG98csIHfT
